//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_cafe_film.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public int Id { get; set; }
        public Nullable<decimal> Domain { get; set; }
        public Nullable<decimal> Hosting { get; set; }
        public Nullable<decimal> MuaPhim { get; set; }
        public Nullable<decimal> BanPhim { get; set; }
        public Nullable<decimal> BaoTri { get; set; }
        public Nullable<decimal> TongSoDu { get; set; }
        public int IdEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
