//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_cafe_film.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieUser
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdMovie { get; set; }
        public string ThoiGianXem { get; set; }
        public string Secsion { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
