//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_cafe_film.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.DetailMovie = new HashSet<DetailMovie>();
            this.RatingOfMovie = new HashSet<RatingOfMovie>();
            this.MovieUser = new HashSet<MovieUser>();
        }
    
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string URLDetail { get; set; }
        public string LinkImage { get; set; }
        public string Descriptions { get; set; }
        public string Director { get; set; }
        public string Writer { get; set; }
        public string Stars { get; set; }
        public Nullable<int> YearProduce { get; set; }
        public string AddressProduce { get; set; }
        public string RunningTime { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string ReleaseAddress { get; set; }
        public byte[] Img { get; set; }
        public Nullable<int> idEmp { get; set; }
        public string New { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailMovie> DetailMovie { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingOfMovie> RatingOfMovie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieUser> MovieUser { get; set; }
    }
}
