//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_cafe_film.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhimChuaKiemDuyet
    {
        public int id { get; set; }
        public Nullable<int> MovieID { get; set; }
        public string MovieName { get; set; }
        public string URLDetail { get; set; }
        public string LinkImage { get; set; }
        public string Descriptions { get; set; }
        public string Director { get; set; }
        public string Writer { get; set; }
        public string Stars { get; set; }
        public Nullable<int> YearProduce { get; set; }
        public string AddressProduce { get; set; }
        public string RunningTime { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string ReleaseAddress { get; set; }
        public byte[] Img { get; set; }
        public Nullable<int> idEmp { get; set; }
        public string @new { get; set; }
        public Nullable<int> CategoryID { get; set; }
    }
}
