//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_cafe_film.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingOfMovie
    {
        public int MaThanhVien { get; set; }
        public int MovieID { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Data { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
